spring:
  datasource:
    url:
      jdbc:h2:mem:testdb
    driverClassName:
      org.h2.Driver
    username:
      felipe
    password:
      12345678
  jpa:
    database-platform:
      org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled:
        true
      path:
        /h2-console